#========================================================
# Say Goodbye
#========================================================

# Put any commands you want to execute on logout here

echo "Goobye $(whoami)"